name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run tests
        run: mvn clean test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Verify JAR exists
        run: ls -la target/

      - name: Build and push Docker image
        run: |
          docker build -t bitbuilder:latest .
          docker save bitbuilder:latest | gzip > bitbuilder.tar.gz

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "bitbuilder.tar.gz,compose.yaml"
          target: "/home/ec2-user/app/"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/app
            
            # Stop existing containers
            docker compose down || true
            
            # Load new Docker image
            docker load < bitbuilder.tar.gz
            
            # Clean up old images
            docker image prune -f
            
            # Start services with Docker Compose
            docker compose up -d
            
            # Clean up tar file
            rm -f bitbuilder.tar.gz